// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJQZb2qTFkJvEhXlhht8ALkF-uYmoSbbc',
    appId: '1:819291672454:web:f8d7c6eb0fba7d8193a607',
    messagingSenderId: '819291672454',
    projectId: 'fir-demo-b2960',
    authDomain: 'fir-demo-b2960.firebaseapp.com',
    databaseURL: 'https://fir-demo-b2960-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-demo-b2960.appspot.com',
    measurementId: 'G-C62N7W3PZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiPmWhO5-QfWvdJEpmyUPflyoBPilGBL8',
    appId: '1:819291672454:android:44dbd674e02aee8993a607',
    messagingSenderId: '819291672454',
    projectId: 'fir-demo-b2960',
    databaseURL: 'https://fir-demo-b2960-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-demo-b2960.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEzM10wkJy3-GhR2hb8iTfsEXow_k9MlY',
    appId: '1:819291672454:ios:dde3d9fa351d026b93a607',
    messagingSenderId: '819291672454',
    projectId: 'fir-demo-b2960',
    databaseURL: 'https://fir-demo-b2960-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-demo-b2960.appspot.com',
    androidClientId: '819291672454-09rjksntk157gpoukaou90n3l8helnor.apps.googleusercontent.com',
    iosClientId: '819291672454-qgjvdod3mbj0ideqi1o28haesjsq0hc4.apps.googleusercontent.com',
    iosBundleId: 'com.kmitl.hydroponic',
  );
}
